FROM node:current-slim

WORKDIR frontend/

COPY package*.json ./

RUN npm install

COPY . .

ENV EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
ENV REACT_NATIVE_PACKAGER_HOSTNAME=${IP_ADDRESS}

EXPOSE ${EXPO_PORT1}
EXPOSE ${EXPO_PORT2}
EXPOSE ${EXPO_PORT3}
EXPOSE ${EXPO_PORT4}

CMD ["npm", "start"]